### ISSUE TITLE
有点好奇如何参与字体设计

### ISSUE THREAD

**Issue by 1262917464** [TakWolf/ark-pixel-font#1]
RT（）

**Comment by TakWolf** [comment]
任何有关字体的意见都可以反馈。
通常是对某个字形的绘制提出改进建议，或提出更好的绘制方案。

所有字形的设计文件均为图片，放置于： https://github.com/TakWolf/ark-pixel-font/tree/develop/assets/design
也可以在线预览目前开发分支快照版本的全部字形：https://ark-pixel-font.takwolf.com/alphabet-12px.html

----------

更进一步，如果你对字体设计有信心，想要参加字形设计，并有长期贡献的打算。
可以尝试自己绘制一部分字形，并提交 PR。这边会考察一下是否符合参与要求。

这是一个标准 Python 项目，自行构建字体非常容易。
绘制字形仅需要常见的像素绘图工具即可（例如 [aseprite](https://github.com/aseprite/aseprite) ）。
