### ISSUE TITLE
谚文什么时候会有

### ISSUE THREAD

**Issue by diaowinner** [TakWolf/ark-pixel-font#13]
RT，我感觉您《缝合怪》里的[Galmuri](https://galmuri.quiple.dev/)的谚文可以改改然后再用这个数据生成。
不过要想实现全部的谚文覆盖的话，就无法考虑BDF等其他字体的条件了，因为要加OpenType表，目前BCF以及PCF都不能使用。
>「丁卯点阵体」虽然看上去是像素的，但并不是老旧的像素字体格式，所有的「像素」都是由轮廓围合出来的。  
>作为一款当代的字体，「丁卯点阵体」配备了丰富的高级排版武器——这是坊间称做「OpenType 特性」的字体功能。在专业的平面设计和排版软件（比如 Adobe InDesign 和 Illustrator）以及网页开发中，它能够让文字以更加灵活的方式呈现。[来源](https://3type.cn/fonts/dinkie_bitmap/)

以上。

**Comment by TakWolf** [comment]
谚文的部分在这里：

https://github.com/TakWolf/hangul-syllables-pixel-generator

已经有思路的，只是还没开始做

**Comment by diaowinner** [comment]
不过关于思路嘛… 我其实现在在整 [k8x12j](//github.com/diaowinner/k8x12j)，于是就想做谚文音节了，突然来了想法。
![谚文设计](https://raw.githubusercontent.com/diaowinner/k8x12j/main/docs/Hangul%20Design.png)
这是我整的网格，这里抛砖引玉一下。但是因为我做这个完全是为了 geek 行为，所以不同大小的谚文会放在专用区。
