### ISSUE TITLE
拆分等宽字体和比例字体

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/ark-pixel-font#14]
比例字体讨论：

https://github.com/TakWolf/ark-pixel-font/discussions/4

拆分后，需要重做西文和标点符号。相关问题：

https://github.com/TakWolf/ark-pixel-font/issues/21

https://github.com/TakWolf/ark-pixel-font/issues/17

版本号机制变更：

https://github.com/TakWolf/ark-pixel-font/issues/15

**Comment by MY1L** [comment]
做比例字体是有坑的，比如`kern`。不过你可以直接抄我的免费字体包含的特性：https://github.com/MY1L/Ctrl/releases/tag/Zpix

**Comment by TakWolf** [comment]
拆分已完成 https://github.com/TakWolf/ark-pixel-font/releases/tag/2022.10.27
