### ISSUE TITLE
更改版本号格式，以及发布机制

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/ark-pixel-font#15]
目前版本号格式为：

`x.y.z-dev-YYYYMMDD`

这预期是一个长期小幅迭代更新的项目，所有尺寸为同时更新发布。因此可能永远无法到达真正意义上的 1.0.0 版本。

因此，计划将字体版本号更改为日期格式，例如：

`2022.06.20`

**Comment by EldersJavas** [comment]
可以用里程碑版本法
比如，完成GB2312是1.0
以此类推

**Comment by diaowinner** [comment]
如果在“真正意义上”是泛CJK的话，完成GB0只能说是0.1罢了。  
可以使用类似 Windows 的 Build 的方式。  
例如：0.1.xxx.dev，字体版就变成 0.1.xxx.release

**Comment by TakWolf** [comment]
@EldersJavas @diaowinner 
目前字符绘制是按照关联部件集中绘制的，而不是单独绘制 GB0 的。

例如，制作 【青】 的时候，一般也会统一绘制：

> 青倩凊请郬啨圊埥婧寈崝情掅淸清猜菁晴棈氰腈靓靔皘睛碃蒨锖靕靖箐精綪聙蔳蜻靗靘静請靚篟輤錆靛靜鲭儬濪瀞靝鯖鶄鼱靑

这样绘制效率最高，并且部件样式会保持统一，但是这其中 GB0 覆盖的不多。

只不过部件选择上，会优先 GB0 比较常见的。

https://github.com/TakWolf/ark-pixel-font/commit/2da414acf06ed9034eca25fcc82b2f6799f4d488

这次提交大概更新了 600 个汉字左右，其中 GB0 大概有 100 多左右

**Comment by TakWolf** [comment]
在 https://github.com/TakWolf/ark-pixel-font/commit/3c77491a8a9c7997011e4ddfc34805e7aa9c8749 完成
