### ISSUE TITLE
Latin字体引号样式出错

### ISSUE THREAD

**Issue by C29H25N3O5** [TakWolf/ark-pixel-font#17]
按照西文排版规范, Latin字体(以及韩语/日语)中这些引号应改为半宽:
<img width="726" alt="Screenshot 2022-05-25 at 14 01 15" src="https://user-images.githubusercontent.com/87485746/170347938-63a26024-754c-4dfc-bd81-b1dc113aa57f.png">

**Comment by TakWolf** [comment]
拉丁语系排版不应该使用 20xx 的引号吧，应该仅使用基础 ascii 区块的。
另外日语和韩语在汉字中也不使用引号，只使用单角号。

所以不会存在这个例子吧？这种属于错误的使用了字符

**Comment by C29H25N3O5** [comment]
<https://fonts.google.com/knowledge/introducing_type/exploring_punctuation>
<img width="783" alt="Screenshot 2022-05-25 at 14 30 13" src="https://user-images.githubusercontent.com/87485746/170352405-de6f1b4a-7f65-4afd-a7e0-dfe29e88b70a.png">

据我在排版的经验和这片Google Fonts文章 拉丁排字应在正式场合使用20xx的引号.

**Comment by C29H25N3O5** [comment]
我确定我的这个例子没有出错 你可以参考别的西文字体 不出意外这些符号应该都是半角(纯西文字体就不存在什么全半角的说法)

**Comment by TakWolf** [comment]
这个问题超出了我的知识范畴。我需要研究一下，或等待其他字体方面的专家给出意见。

是否有比较权威的【等宽 CJK 矢量字体】可供参考，它们在这里是如何处理的？

**Comment by C29H25N3O5** [comment]
我这里只是针对Latin字体.
据我所知, 绝大部分等宽西文字体均无CJK支持.

个人观点:
* 如果是兼容CJK, 那么`‘’“”`(U+2018, U+2019, U+201C, U+201D)可为全角形式, 但U+201A, U+201B, U+201E, U+201F为德语引号所以应该仍为半角形式.
* 如果是只支持拉丁排版习惯, 这些引号全部应该改为半角形式.

顺便刚才也去看了一下,
* 思源黑体(Source Han Sans)的简中和繁中的U+2018, U+2019, U+201C, U+201D是全角形式, 但其他引号(uni201A, uni201E)为半角形式;
* Source Han Sans的日语和韩语字体均为半角引号(个人认为是因为这两种语言只使用方引号的缘故\[「」『』\])

**Comment by TakWolf** [comment]
我验证了一下思源黑体，确实是这样。

计划会遵从思源黑体的处理方式，【简台港传】使用全角，其余使用半角。

除了引号、尖括号之外，该问题还设计其他字符吗？

**Comment by C29H25N3O5** [comment]
还有这两个prime在所有字体下都应该为半角:
<img width="182" alt="Screenshot 2022-05-25 at 15 15 22" src="https://user-images.githubusercontent.com/87485746/170359484-059bd0ed-33fa-4bfc-9c8c-27346ab1dff4.png">
(这两个符号是用于表示时分秒的 和CJK不搭边)

**Comment by MY1L** [comment]
这个是统一码不区分全角半角弯引号的问题，新人常见的坑，一般中文做全角西文做半角，但中文还有个标点挤压问题，弯引号需要有半角形式……
我做的像素字体则通过OT特性来同时支持全\半角弯引号（非`locl`特性，因为我懒）https://github.com/MY1L/Ctrl/releases/tag/Zpix
顺带这个**蝌蚪形**弯引号不适合西文字体，请参考我的做法。

**Comment by TakWolf** [comment]
CtrlZipx 的方案 
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/6064962/170426585-659413a0-d946-4989-9fa9-8631c9d60b79.png">

**Comment by C29H25N3O5** [comment]
<img width="675" alt="Screenshot 2022-05-26 at 14 01 10" src="https://user-images.githubusercontent.com/87485746/170558300-b6fcd9c8-b53b-4354-88b7-31de31aee70c.png">
我自己的CHNO Pixel Code的方案(无CJK支持)
https://github.com/C29H25N3O5/CHNO-Pixel-Code-Pro

**Comment by P03T-life** [comment]
> 是否有比较权威的【等宽 CJK 矢量字体】可供参考，它们在这里是如何处理的？

等距更纱黑体。

![等距更纱黑体里头的引号](https://user-images.githubusercontent.com/43498546/170787538-a348869d-cbf8-44d1-948d-e2aaf3f8331b.png)

**Comment by TakWolf** [comment]
引号问题已经在 https://github.com/TakWolf/ark-pixel-font/releases/tag/2022.10.27 中修复
