### ISSUE TITLE
16px字体下小写字母rho基线出错

### ISSUE THREAD

**Issue by C29H25N3O5** [TakWolf/ark-pixel-font#18]
<img width="1010" alt="Screenshot 2022-05-25 at 14 41 17" src="https://user-images.githubusercontent.com/87485746/170354057-97160a51-8b4b-40f5-b598-c75deecf4df5.png">
如图, 16px字体下小写字母rho的bowl没有和baseline对齐.

**Comment by TakWolf** [comment]
这个问题没太懂。是指这两个希腊字母基线位置有问题？

**Comment by C29H25N3O5** [comment]
应当如此:
<img width="943" alt="Screenshot 2022-05-25 at 15 21 56" src="https://user-images.githubusercontent.com/87485746/170360448-8b4f15ce-ad4e-4d1f-8336-9eff0be3a844.png">

**Comment by TakWolf** [comment]
16px `ρ` u03C1

**Comment by TakWolf** [comment]
已在 https://github.com/TakWolf/ark-pixel-font/releases/tag/dev-2022-06-08 中修复
