### ISSUE TITLE
`uni00DF` 德语eszett(ß)样式出错

### ISSUE THREAD

**Issue by C29H25N3O5** [TakWolf/ark-pixel-font#20]
https://en.wikipedia.org/wiki/ß
<img width="338" alt="Screenshot 2022-05-25 at 14 44 52" src="https://user-images.githubusercontent.com/87485746/170354601-0a4e2ea3-b757-4d47-aa1e-357354553dd7.png">

根据这篇Wikipedia文章, uni00DF (ß)历史上是一个long s (ſ)和一个普通s的连字, 虽然形似beta但没有任何关系.
根据字形设计习惯, 这个符号左下角不应该封口.
<img width="341" alt="Screenshot 2022-05-25 at 14 47 04" src="https://user-images.githubusercontent.com/87485746/170354935-18761bd0-7e4a-42d4-800f-2e89546afe16.png">
<img width="341" alt="Screenshot 2022-05-25 at 14 47 37" src="https://user-images.githubusercontent.com/87485746/170355005-365559cf-b7b2-45e6-a41c-8615c38e34bb.png">

**Comment by TakWolf** [comment]
已在 https://github.com/TakWolf/ark-pixel-font/releases/tag/dev-2022-06-08 中修复
