### ISSUE TITLE
希腊文大写字母tonos样式出错

### ISSUE THREAD

**Issue by C29H25N3O5** [TakWolf/ark-pixel-font#21]
<img width="1225" alt="Screenshot 2022-05-25 at 14 49 41" src="https://user-images.githubusercontent.com/87485746/170355377-2be929f7-9789-403b-98ac-cbd2ccfe10dc.png">
(Wikipedia)
<img width="1225" alt="Screenshot 2022-05-25 at 14 50 13" src="https://user-images.githubusercontent.com/87485746/170355399-0de40b21-9c35-4884-ba03-3ae0f5f6aac0.png">
希腊文习惯, 大写字母变音符应放置于字母左侧.
<img width="243" alt="Screenshot 2022-05-25 at 14 51 05" src="https://user-images.githubusercontent.com/87485746/170355543-b37257b0-b7a7-4e71-84d2-4612363bb8a1.png">
(SF Pro Display Bold)

**Comment by C29H25N3O5** [comment]
根据我个人的诠释...
<img width="1334" alt="Screenshot 2022-05-25 at 15 27 50" src="https://user-images.githubusercontent.com/87485746/170361381-1e0b2758-706f-43e7-a3de-dd3a7071d0d3.png">

**Comment by TakWolf** [comment]
我不太懂希腊语，这个思源黑体点在右边？

<img width="253" alt="image" src="https://user-images.githubusercontent.com/6064962/170361149-aaf592a9-a7fe-4743-8ea7-3ae694b76bbe.png">

另外只有大写字母在左侧吗？小写字母仍然在上面吗？

当时这么画是因为等宽模式下左侧没有空余空间了

**Comment by C29H25N3O5** [comment]
<img width="1334" alt="Screenshot 2022-05-25 at 15 30 49" src="https://user-images.githubusercontent.com/87485746/170361723-da0f4751-ad59-4e58-938c-33a646622c54.png">
这个是Source Sans Pro的处理方式

**Comment by MY1L** [comment]
> 我不太懂希腊语，这个思源黑体点在右边？
呃……思源黑体不含带变音符的大写字母希腊文，你图里的是无关的后备字形。
我是这么做的：https://github.com/MY1L/Ctrl/releases/tag/Zpix 
等宽字体可以考虑放左上角。

**Comment by TakWolf** [comment]
<img width="1729" alt="image" src="https://user-images.githubusercontent.com/6064962/170424650-ce383052-19a9-4e18-a4a2-0d282cfead43.png">

CtrlZpix 的方案

**Comment by TakWolf** [comment]
到 https://github.com/TakWolf/ark-pixel-font/commit/89cbd8720fe6b76a1be1a9621fc347f1113df17f 节点为止，已完成对 希腊字母 段的重绘
