### ISSUE TITLE
python -m pip install -r requirements.txt

### ISSUE THREAD

**Issue by vlanskc** [TakWolf/ark-pixel-font#23]
$ python -m pip install -r requirements.txt
Collecting beautifulsoup4==4.11.1
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
......................
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe==2.1.1
  Using cached MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
ERROR: Could not find a version that satisfies the requirement minify_html==0.8.0 (from -r requirements.txt (line 8)) (from versions: 0.2.6, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 0.5.0, 0.5.2, 0.5.3, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10)
ERROR: No matching distribution found for minify_html==0.8.0 (from -r requirements.txt (line 8))

**Comment by TakWolf** [comment]
你这里似乎是 minify_html 依赖获取有问题，但是这个版本是有的

<img width="430" alt="image" src="https://user-images.githubusercontent.com/6064962/170813161-7365c8b6-b343-40f0-afdd-f4bddb2a2730.png">

https://pypi.org/project/minify-html/

https://github.com/wilsonzlin/minify-html/releases/tag/v0.8.0

**Comment by TakWolf** [comment]
重新测试后目前 master 分支并不存在构建问题，暂时不清楚你构建失败的原因。

你可以尝试将  requirements.txt 中 minify_html 版本改为 0.6.10，之后重新安装依赖。

我暂时将这个问题关闭。

有任何问题，请随时回复并重新打开这个线程。
