### ISSUE TITLE
homebrew-fonts 构建需要按照比例和等宽模式拆分

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/ark-pixel-font#26]
@singularitti  从版本 [2022.10.27](https://github.com/TakWolf/ark-pixel-font/releases/tag/2022.10.27) 开始，拆分了等宽和比例模式，homebrew-fonts 构建需要重新规划。预计修改成这样：

- 等宽模式

```commandline
brew install font-ark-pixel-10px-monospaced
brew install font-ark-pixel-12px-monospaced
brew install font-ark-pixel-16px-monospaced
```

- 比例模式

```commandline
brew install font-ark-pixel-10px-proportional
brew install font-ark-pixel-12px-proportional
brew install font-ark-pixel-16px-proportional
```

另外，构件的名字重新做的规划。

这样修改会有问题吗？

**Comment by singularitti** [comment]
可以的，cask-font 的[原则](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md#multiple-fonts-per-cask)是：

> Multiple font faces or families are often supplied in a single distribution. When fonts are distributed together, they should be installed together. Each Cask should correspond to a single binary distribution, not necessarily a single font face.
> 
> Similarly, different weights of the same font may be distributed in separate binaries. Here we follow the same rule: each distribution equals a separate Cask.
> 
> This constraint may change in the future, when the backend Ruby code becomes more sophisticated.

也就是根据你的需求来的。

**Comment by TakWolf** [comment]
懂了，那应该没什么问题

**Comment by TakWolf** [comment]
https://github.com/TakWolf/homebrew-cask-fonts/commit/2937b6699dc16db38985a0d492acb85faa283b83
https://github.com/TakWolf/homebrew-cask-fonts/tree/ark-pixel

这样修改是正确的吗？我可以直接用这个分支PR吗？

**Comment by singularitti** [comment]
> [TakWolf/homebrew-cask-fonts@2937b66](https://github.com/TakWolf/homebrew-cask-fonts/commit/2937b6699dc16db38985a0d492acb85faa283b83) https://github.com/TakWolf/homebrew-cask-fonts/tree/ark-pixel
> 
> 这样修改是正确的吗？我可以直接用这个分支PR吗？

简单看了一下，应该是对的。

**Comment by TakWolf** [comment]
PR 跟踪：

https://github.com/Homebrew/homebrew-cask-fonts/pull/6509

**Comment by singularitti** [comment]
它说你 "missing description", 你可以在每个 cask 的下面加一行

> desc: "Open source Pan-CJK pixel font"

Doc: https://docs.brew.sh/Cask-Cookbook#stanza-desc

**Comment by TakWolf** [comment]
PR 已合并，新脚本已测试正常工作。

非常感谢技术指导！！！

**Comment by singularitti** [comment]
举手之劳，不客气。

**Comment by TakWolf** [comment]
@singularitti 请教一个问题。

最新的 2023.03.08 PR 提示  missing zap: Cask is missing a zap stanza, please add one.

搜了一下，好像是这样的：https://github.com/Homebrew/homebrew-cask/commit/f5d9cb1ab54d5a1a9e0c769d7a701d681c4900d5

但是貌似字体仓库的 cask 都没有 zap

这个节点的作用是什么，需要添加吗？

**Comment by TakWolf** [comment]
补充 zap 的文档

https://docs.brew.sh/Cask-Cookbook#stanza-zap

**Comment by singularitti** [comment]
> 补充 zap 的文档
> 
> https://docs.brew.sh/Cask-Cookbook#stanza-zap
> 
> 看起来字体似乎不需要这个节点

对，不需要
