### ISSUE TITLE
与Minecraft & Zpix字体对比

### ISSUE THREAD

**Issue by atjiu** [TakWolf/ark-pixel-font#30]
**Minecraft负责显示英文，Zpix负责显示中文**

- Ark Pixel Font的显示效果

  ![image](https://user-images.githubusercontent.com/6915570/223028767-6974d405-c10a-4ba9-a9c0-5033f505d654.png)

- Minecraft&Zpix的显示效果

  ![image](https://user-images.githubusercontent.com/6915570/223028831-f64dd4d1-05f4-4ee6-9dd2-0b83ce8c6f63.png)

**中文显示上效果差不多，但英文显示上我感觉还是Minecraft的字体要好看些**

**Comment by atjiu** [comment]
Ark Pixel 和 Fusion Pixel 这两款字体在IDE里的表现都不是很好看，有兴趣可以下载一下Minecraft字体在VSCode或IDEA里对比一下 😄

**Comment by atjiu** [comment]
我用的是这个Minecraft字体 
[minecraft-font.zip](https://github.com/TakWolf/ark-pixel-font/files/10894853/minecraft-font.zip)

**Comment by TakWolf** [comment]
这是因为 Ark Pixel 的西文是要和汉字字形尺寸匹配，以保证混排大小合适。以 12px 比例模式为例，汉字字形尺寸是 11*11px，西文字形大写字母高度尺寸就必须要 9px，以这个大小为基准来设计其他字母。这里一定会牺牲一部分西文的美观性。

如果只考虑西文，可以有更好的演绎方式，比如这个：

Cure Mono:  <-- 等宽体适合控制台和 IDE
https://github.com/TakWolf/retro-pixel-font#cute-mono
https://retro-pixel-font.takwolf.com/cute-mono/demo.html

Cute Prop:
https://github.com/TakWolf/retro-pixel-font#cute-prop
https://retro-pixel-font.takwolf.com/cute-prop/demo.html

这个小写字母尺寸也是 5px 高，上升和下沉固定为2px，我个人认为比 Minecraft 尺寸更合理（不考虑风格问题的话）。

**Comment by atjiu** [comment]
原来如此，谢谢
