### ISSUE TITLE
预览网站字体错误。

### ISSUE THREAD

**Issue by tiger2005** [TakWolf/ark-pixel-font#8]
例如说 https://ark-pixel-font.takwolf.com/demo-12px.html ，红字显示的字体并非像素字体，而是下一级字体，即 sans-serif。
![5@XS3JB5I~EEL XB433}9}O](https://user-images.githubusercontent.com/41613797/151985092-d118b4d2-3738-4310-bc88-4b51250666c7.png)

**Comment by TakWolf** [comment]
红字是目前缺少的字，所以才标红的

**Comment by tiger2005** [comment]
草，抱歉
